# Generated by Django 4.2.9 on 2024-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NEWSLETTER',
        ),
    ]
