# Generated by Django 4.2.9 on 2024-02-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240212_1328'),
    ]

    operations = [
        migrations.RenameModel('Sik', 'Category')

    ]
