# Generated by Django 4.2.9 on 2024-02-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240212_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
